name: Build ETISS

on:
  repository_dispatch:
    types: [s4e_cdl_event, seal5-event]
#push:
 #   branches: [ "master" ]
 # pull_request:
 #   branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  setup-run-M2ISAR:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
      with:
        path: etiss_source
        
    - name: Download Core-DSL-Extension Artifacts
      uses: actions/download-artifact@v4
      with:
        name: riscv-core-dsl-files
        github-token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: kebi-be/riscv-coredsl-extensions
        run-id: ${{ github.event.client_payload.run_id }} 

    - name: Install dependencies
      run: |
        sudo apt-get update
        pip install virtualenv
    
    - name: Setup M2-ISA-R
      run: |
       git clone https://github.com/tum-ei-eda/etiss_arch_riscv.git --recursive --branch coredsl_exceptions
       git clone https://github.com/tum-ei-eda/M2-ISA-R.git --branch coredsl2
       cd M2-ISA-R
       virtualenv -p python3.10 venv  #Alternative (requires `apt install python3-venv`): python3 -m venv venv
       source venv/bin/activate
       pip install -e .

    - name: Run M2-ISA-R
      run: |
        ls -al
        cd M2-ISA-R
        python -m m2isar.frontends.coredsl2.parser ../riscv-core-dsl-files/s4e-mac.core_desc
        python -m m2isar.backends.etiss.writer $pwd/gen_model/etiss-s4e-mac.m2isarmodel --separate --static-scalars
      
    - name: Upload M2ISAR Model artifacts
      uses: actions/upload-artifact@v4
      with:
         name: m2isar-model-files
         path: |
            $pwd/gen_model
            
  patch-etiss-arch:
    runs-on: ubuntu-22.04
    needs: [setup-run-M2ISAR]
    steps:
    - name: Download Core-DSL-Extension Artifacts
      uses: actions/download-artifact@v4
      with:
        name: riscv-core-dsl-files
        github-token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: kebi-be/riscv-coredsl-extensions
        run-id: ${{ github.event.client_payload.run_id }}
    
    - run: |
       cp -r extensible-compiler/RISCV-CoreDSL-Extensions/gen_output/etiss-s4e-mac/* etiss/ArchImpl/
       cd etiss
       cp ArchImpl/RV32IMACFD/RV32IMACFDArchSpecificImp.cpp ArchImpl/RV32IMCXS4EMAC/RV32IMCXS4EMACArchSpecificImp.cpp
       sed -i "s/RV32IMACFD/RV32IMCXS4EMAC/g" ArchImpl/RV32IMCXS4EMAC/RV32IMCXS4EMACArchSpecificImp.cpp
       cd -

       cd etiss
       git add --all
       git commit -m 'update etiss architectures'
       cd -

       - name: print trigger details
       run: |
        echo ${{ github.event.client_playload.github.action }}
        echo ${{ github.event.client_playload.github.action }}
        sudo apt -qq install -y build-essential git cmake libboost-system-dev libboost-filesystem-dev libboost-program-options-dev
 
  build-etiss:
    runs-on: ubuntu-22.04
    needs: [patch-etiss-arch]
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-filesystem-dev libboost-program-options-dev \
          llvm-11-dev libclang-11-dev clang-11

    - name: CMake config
      run: |
        cmake -B etiss_build -S etiss_source -DCMAKE_INSTALL_PREFIX=etiss_prebuilt -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        
    - name: CMake build
      run: |
        cmake --build etiss_build -j$(nproc)
        
    - name: CMake install
      run: |
        cmake --build etiss_build --target install
        
    - name: Upload compiled ETISS
      uses: actions/upload-artifact@v4
      with:
        name: etiss_prebuilt
        path: etiss_prebuilt
        
     

    
  test:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    steps:
   # - name: Download build artifact
    #  uses: actions/download-artifact@v4
     # with:
      #  name: etiss-build-files
       # github-token: ${{ secrets.REPO_ACCESS_TOKEN }}
       # repository: ${{ github.repository }}
       # run-id: ${{ github.run_id }}
        
    - name: Download Cached GCC Binaries
      id: cache-gcc
      uses: actions/cache@v4
      env:
        cache-name: cache-gcc-binaries
      with:
        path: ./gnu
        key: gcc-binaries-${{ steps.date.outputs.date }}
        restore-keys: |
          gcc-binaries-
            
    - if: ${{ steps.cache-gcc.outputs.cache-hit != 'true' }}       
      name: Download RISCV-GNU-Toolchain   
      run: |
         wget https://syncandshare.lrz.de/dl/fi2p5Ds5PHktjmZGKzR9tx/GCC/default/2023.09.27/Ubuntu/22.04/rv32imc_ilp32.tar.xz
         tar xvf rv32imc_ilp32.tar.xz
         rm rv32imc_ilp32.tar.xz
         ls -al
         pwd
    
    - name: Build ETISS RISCV Examples for Testing
      run: |
        pwd
        sudo apt -qq install -y build-essential make clang g++ git cmake libboost-system-dev libboost-filesystem-dev libboost-program-options-dev
        git clone https://github.com/tum-ei-eda/etiss_riscv_examples.git --branch philippvk --recursive
        RISCV_GCC_PREFIX=/home/runner/work/etiss_wysiwyng/etiss_wysiwyng/gnu
        RISCV_GCC_NAME=riscv32-unknown-elf
        ARCH=rv32imc
        ETISS_ARCH=RV32IMACFD
        PROG=hello_world
        ABI=ilp32
        export PATH=$RISCV_GCC_PREFIX/bin/:$PATH
        echo $PATH
        pwd
        ls -al
        cd gnu
        pwd
        ls -al 
        cd ..
        cd etiss_riscv_examples         
        mkdir build && cd build
        make --version
        #cmake -DCMAKE_TOOLCHAIN_FILE=rv32gc-toolchain.cmake -DRISCV_TOOLCHAIN_PREFIX=$RISCV_GCC_PREFIX -DCMAKE_INSTALL_PREFIX=../install ..

        #cmake  -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_TOOLCHAIN_FILE=/home/runner/work/etiss_wysiwyng/etiss_wysiwyng/etiss_riscv_examples/rv32gc-llvm-toolchain.cmake -DRISCV_TOOLCHAIN_PREFIX=/home/runner/work/etiss_wysiwyng/etiss_wysiwyng/gnu -DCMAKE_INSTALL_PREFIX=../install ..
        cmake -DCMAKE_TOOLCHAIN_FILE=/home/runner/work/etiss_wysiwyng/etiss_wysiwyng/etiss_riscv_examples/rv32gc-llvm-toolchain.cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/install -DRISCV_ARCH=$ARCH -DRISCV_ABI=$ABI -DRISCV_TOOLCHAIN_PREFIX=$RISCV_GCC_PREFIX -DRISCV_TOOLCHAIN_BASENAME=$RISCV_GCC_NAME ..
        make -j$(nproc) install    
        make install
    - name: Run ETISS Default Configuration Test
      run: |
        echo "Finished"
        #etiss-build-files/bin/bare_etiss_processor -i'pwd'/install/ini/hello_world.ini
    needs: build-etiss
